// Primary-source abstracts from the discovery queue; MetaGPT uses the cited full-text section.
const U='Not specified in the abstract';
const rows = [
 ['2609.20130','AdaRepair-Mem',['experience','governance'],['explore','debug','test','reflect'],
  'Routes repair experience by workflow stage and adjusts retrieval for repositories with sparse history. Selection considers relevance, utility, specificity, and redundancy instead of simply increasing memory volume.',
  'Repair experiences organized by repository and repair phase',{retrieve:'Coverage-aware fallback with quality-aware selection and stage-aware routing'},
  'SWE-bench Lite and Verified','Benefits depend on memory coverage and repair phase; more memory is not monotonically better.'],
 ['2609.07357','EnvPilot',['experience','skills'],['explore','plan','test'],
  'Converts prior environment-setup trajectories into structured guidance. Context-aware retrieval supplies validated setup strategies for new repositories and programming ecosystems.',
  'Expandable trajectory-derived setup memory',{write:'Transform historical execution traces into structured experiences',retrieve:'Context-aware retrieval during environment setup',update:'Expand the trajectory-derived memory'},
  'AES-Bench: 112 GitHub instances across nine languages','Environment setup success is distinct from code-patch correctness.'],
 ['2609.05510','SIx Harness',['repository','governance','evaluation'],['code','debug','reflect','maintain'],
  'Treats persistent project memory as operational infrastructure. Local retrieval, decision and dead-end stores, session-start health checks, and failure telemetry support a months-long coding project.',
  'Local SQLite memory and compaction-resistant decision stores',{write:'Capture project knowledge and failed approaches',retrieve:'Hybrid lexical-vector retrieval with precision-gated injection',update:'Health gates and telemetry monitor memory continuity'},
  'Instrumented months-long software development deployment','Single self-reported project with no control arm; operational reliability does not establish a causal coding improvement.'],
 ['2608.20685','MemStrata / Temporal Validity',['repository','governance','evaluation'],['code','debug','maintain'],
  'Tracks which retained software facts have been superseded by repository changes. A deterministic relation-based memory distinguishes current values from stale ones when similar facts compete in retrieval.',
  'Subject-relation-object facts with temporal supersession',{write:'Extract clean value transitions from GitHub fixes',retrieve:'Answer with the current fact',update:'New facts supersede older values',forget:'Exclude superseded values from current answers'},
  '130 atomic state transitions from SWE-bench histories','Only clean atomic transitions are evaluated; broader software changes remain outside reported coverage.'],
 ['2608.09181','Memoir',['experience','governance','skills'],['review','test','reflect'],
  'Builds reusable memories from historical false-positive security alerts. Retrieved patterns undergo semantic checks before classification, and verified predictions feed the memory repository.',
  'Structured semantic memories of false-positive alert patterns',{write:'Annotate and cluster alerts, then synthesize memories',retrieve:'Retrieve patterns and check security invariants',update:'Incorporate verified predictions'},
  'CWE-Bench-Java and an industrial SAST case study','Security alert classification is a specialized software workflow, not a general issue-repair benchmark.'],
 ['2608.06811','PMCoder',['experience','context','governance'],['explore','plan','debug','test'],
  'Couples a hierarchical repair planner with episodic memory. The active phase conditions retrieval, while memory statistics detect repeated failures and trigger replanning; execution verdicts ground verification.',
  'Episodic observations coupled to a hierarchical phase plan',{write:'Retain observations and trajectory statistics',retrieve:'Condition retrieval on the current plan phase',update:'Memory statistics trigger stuck detection and replanning'},
  'SWE-bench Verified and a TerminalWorld sample','Effects of the coupled planner and memory can depend on the surrounding harness.'],
 ['2608.04278','EA-Graph',['repository','governance','evaluation'],['review','test','maintain'],
  'Anchors verification claims to the precise artifacts that supported them. After upstream changes, it separates unaffected, affected, and unprovable claims rather than treating old prose notes as current evidence.',
  'Artifact-level claim graph with content anchors and freshness',{write:'Record claims with supporting artifact content',retrieve:'Resolve aliases and inspect claim dependencies',update:'Reassess claims when supporting content changes',forget:'Mark unavailable replacement evidence as unprovable'},
  'Generated repositories with known artifact ground truth','Controlled testbed supports provability judgments; the paper does not establish repair quality or efficiency gains.'],
 ['2608.00122','Organizational Memory',['collaboration','experience','governance'],['code','reflect','maintain'],
  'Captures development experience at the platform level with contributor approval. Curated question-answer memories are shared with future coding agents after security and privacy gates.',
  'Shared organizational question-answer experience memory',{write:'Capture approved task-adjacent experience',retrieve:'Retrieve organizational knowledge for future agents',update:'Curate captured experience into reusable records'},
  'Ongoing enterprise deployment snapshot','Retrieval and coding-task effects remain under evaluation.','cross-framework'],
 ['2607.20972','Cue-Anchored Memory',['context','repository','governance'],['explore','code','debug','maintain'],
  'Associates operational memories with path, symbol, semantic, event, and temporal cues. The harness injects matching facts deterministically so delivery does not depend on agents choosing to consult a store.',
  'Operational facts with composable trigger conditions',{write:'Incidentally encode situational knowledge during work',retrieve:'Harness evaluates cues and injects matching memories',update:'Preserve continuity across compactions'},
  'Controlled coding task and repeated-compaction probes','Narrow operational probes do not establish general repair-performance improvements.'],
 ['2607.14390','Git-Bound Memory',['repository','governance','experience'],['explore','plan','review','maintain'],
  'Links coding-session reasoning to commits. A query router separates structural lookups, confidence-gated episodes, and decision rationale, using repository history and review to govern memory freshness.',
  'Git-linked session ledger, structural map, and decision synthesis',{write:'Capture reasoning and link sessions to commits',retrieve:'Route queries to maps, episodes, or rationale synthesis',update:'Rebuild from commit-linked history'},
  'Eight-corpus retrieval study and developer-question evaluation','Retrieval rankings and answer sufficiency measure different outcomes; reported results are corpus-specific.'],
 ['2607.01916','ContextSniper',['context','repository','experience'],['explore','debug','test'],
  'Indexes code and action memory at multiple levels, retrieves compact evidence packets, and filters tool output according to intent. Original source remains recoverable when a repair agent needs detail.',
  'Three-level code and action memory with recoverable source',{write:'Index code and action evidence',retrieve:'Hybrid ranking with an intention-aware gate',forget:'Filter delivered context while preserving recoverable source'},
  'Matched 50-task comparisons on SWE-bench Lite and Pro','One-task resolution differences do not establish broad accuracy equivalence.'],
 ['2606.23752','ESAA-Conversational',['collaboration','repository','governance'],['plan','code','reflect','maintain'],
  'Normalizes conversations from different coding assistants into an append-only event log. Deterministic projections produce handoff notes, task lists, and decisions; agents explicitly curate durable knowledge.',
  'Shared event store with projected handoff and task records',{write:'Hooks capture turns; explicit commands curate decisions',retrieve:'Read deterministic projections for handoff',update:'Append events and rebuild projections',forget:'Public distributions omit private history'},
  'Self-referential development-lab case study','Demonstrates integration feasibility rather than controlled productivity improvement.','cross-framework'],
 ['2606.12329','PROJECTMEM',['repository','governance','experience'],['plan','debug','reflect','maintain'],
  'Records issues, attempts, fixes, decisions, and notes as typed events. Compact projections supply project context, while a pre-action gate warns about repeated failed fixes and fragile files.',
  'Append-only project event log and deterministic summaries',{write:'Record typed development events',retrieve:'Serve compact projections through MCP',update:'Append events and update read projections',forget:'Immutable log; deletion is not described'},
  'Two-month self-study across ten projects','Self-study and estimated context costs do not establish general causal benefits.'],
 ['2606.08151','Decision-Aware Cards',['context','governance'],['explore','plan','debug'],
  'Selects files, tests, traces, and rules for their expected effect on the next action. An instance graph supports utility ranking, and chosen evidence becomes compact typed memory cards.',
  'Instance context graph and typed evidence cards',{write:'Compress selected evidence into cards',retrieve:'Rank evidence by decision-oriented utility',forget:'Exclude low-utility context from delivered cards'},
  '50 SWE-bench Verified file-retrieval instances and diagnostics','Retrieval and context savings do not establish end-to-end patch correctness.'],
 ['2605.30842','CoMem',['context','collaboration'],['code','debug','test'],
  'Separates the coding agent from a trained memory model that summarizes history asynchronously. Overlapping memory processing with inference aims to reduce latency while preserving decision context.',
  'Summaries from a decoupled long-context memory model',{write:'Summarize previous interactions',retrieve:'Consume asynchronously delivered summaries',update:'Update summaries through a k-step-off pipeline'},
  'SWE-bench Verified and throughput experiments','Asynchronous memory can lag the task; tradeoffs depend on compression training and serving conditions.','multi-agent'],
 ['2605.17444','MemRepair',['experience','repository','skills'],['debug','test','reflect'],
  'Combines prior fixes, security patterns, and refinement trajectories in layered memory. Runtime feedback directs reuse of repository conventions and earlier failed-to-successful repair paths.',
  'History-Fix, Security-Pattern, and Refinement-Trajectory memories',{write:'Retain fixes, defenses, and refinement experience',retrieve:'Retrieve conventions, defenses, and prior trajectories',update:'Runtime feedback drives iterative refinement'},
  'SEC-Bench, PatchEval, and a Multi-SWE-bench C++ subset','Specialized vulnerability-repair results differ from general software maintenance.'],
 ['2605.14563','MemDocAgent',['repository','context'],['explore','review','maintain'],
  'Keeps earlier documentation work in repository memory as an agent traverses dependencies. Read, write, and verification operations aim to avoid repeated retrieval and inconsistent descriptions.',
  'RepoMemory accumulating repository documentation traces',{write:'Write prior documentation work traces',retrieve:'Read memory during dependency-aware traversal',update:'Verify accumulated work'},
  'Multi-criteria repository documentation evaluation','Documentation quality is different from executable code correctness.'],
 ['2605.08468','PYTHALAB-MERA',['experience','skills','governance'],['code','debug','test','reflect'],
  'Places a memory-and-retrieval controller around a frozen coding model. It chooses episodic records and structural skills, validates generated files, and credits retrieval decisions through execution feedback.',
  'Validation-grounded episodic memory and AST-derived skills',{write:'Retain validation outcomes and reusable knowledge',retrieve:'Controller selects records and skills for prompts',update:'Rewards and eligibility traces assign delayed credit'},
  'Three RL coding tasks with repeated strict validations','A small bounded study does not establish general synthesis or formal correctness.'],
 ['2608.20342','PrimeAgentOrchestrator',['collaboration','repository','context'],['plan','code','maintain'],
  'Preloads new coding-agent sessions with briefings compiled from two memory backends. Parallel retrieval, result fusion, and file-based delivery bridge heterogeneous knowledge stores.',
  'Compiled briefing from entity-observation and semantic memories',{write:'Uses existing personal stores; write policy is unspecified',retrieve:'Query stores in parallel and fuse results at session start',update:'Rebuild briefings for new sessions'},
  'Four-month deployment experience report','Reports tradeoffs and failure modes rather than controlled task-success gains.','cross-framework'],
 ['2604.27283','Risk-Sensitive Retrieval',['governance','experience'],['debug','test','reflect'],
  'Makes memory use a selective decision: inject, summarize, retrieve differently, abstain, or request feedback. A contextual bandit considers compatibility, uncertainty, risk, and cost before debugging experience influences an agent.',
  'Pattern-variant-episode issue memory with retrieval telemetry',{write:'Store reusable debugging experience',retrieve:'Controller chooses retrieval or abstention',update:'Feedback informs rewards and controller behavior',forget:'Suppress risky injections; deletion is unspecified'},
  'Deterministic replay and bounded 200-case validation','Proxy success and smoke-scale artifacts do not establish broad software-repair performance.'],
 ['2608.24188','Paritok-4B',['context','governance'],['explore','code','debug'],
  'Compresses tool output by selecting exact spans conditioned on the task. Extractive retention aims to preserve code identifiers and edit locations more reliably than prose paraphrasing.',
  'Intent-conditioned retained spans from file reads and tool output',{write:'Distill trajectories into compression examples',retrieve:'Deliver selected spans as compressed context',update:'Task intent conditions span selection',forget:'Remove unselected spans from delivered context'},
  'OpenHands trajectories and SWE-bench Lite single-shot solving','Non-significance is not equivalence; single-shot quality does not establish multi-turn savings.'],
 ['2609.22114','Compression Cost Attribution',['context','evaluation'],['code','debug','test'],
  'Separates schema filtering, source compression, and history summarization when measuring coding-agent cost. It studies how compressed reads accumulate in later prompts and how original-source recall spends savings back.',
  'Compressed outputs, filtered schemas, and summarized histories',{write:'Gateway compresses reads during coding work',retrieve:'Recall original source on demand',update:'Compressed reads accumulate in later history',forget:'Filtering and summarization alter delivered context'},
  'Controlled A/B multi-turn coding sessions','Single-shot quality differs from cache-priced multi-turn economics.'],
 ['2601.06789','MemGovern',['experience','repository','governance'],['explore','debug','reflect'],
  'Transforms fragmented GitHub issue history into structured experience cards. Agentic search retrieves governed human repair knowledge instead of starting every issue from scratch.',
  'Governed experience cards from GitHub history',{write:'Convert issue-tracking data into experience cards',retrieve:'Logic-driven search over governed experience',update:'Governance structures and curates human history'},
  'SWE-bench Verified','Card quality and historical availability condition usefulness; deletion policies are not established.'],
 ['2303.11366','Reflexion',['experience','context'],['code','test','reflect'],
  'Turns task feedback into verbal reflections retained in an episodic buffer. Agents consult those reflections on subsequent attempts, including code generation, without changing model weights.',
  'Episodic buffer of verbal self-reflections',{write:'Reflect on numeric or language feedback',retrieve:'Use reflections in subsequent attempts',update:'Append feedback-derived reflections'},
  'Reasoning, decision-making, and coding including HumanEval','Coding is a relevant application, but this broader method predates repository-level repair benchmarks.'],
 ['2308.00352','MetaGPT',['collaboration','context'],['plan','code','debug','test'],
  'Uses a shared pool of structured messages to coordinate software roles. Agents publish artifacts, subscribe to relevant information, and revisit stored messages while debugging against requirements and design.',
  'Shared structured message pool and agent message history',{write:'Publish structured requirements, designs, and implementation messages',retrieve:'Role-based subscriptions filter shared messages',update:'Execution feedback prompts agents to revisit work',forget:'Cross-task forgetting policy is not established by the cited section'},
  'Collaborative software development, HumanEval, and MBPP','Shared task memory is one component of the framework; overall results do not isolate its effect.','multi-agent'],
 ['2407.15568','AgileGen',['collaboration','experience'],['plan','code','test'],
  'Collects user decision scenarios in a memory pool and recommends them during later requirement elicitation. Human-AI iterations connect testable requirements to generated software.',
  'Memory pool of user decision-making scenarios',{write:'Collect user decision scenarios',retrieve:'Recommend scenarios to new users'},
  'Generative software development and user satisfaction','Overall system comparisons combine memory, requirement representation, and interaction design.'],
 ['2507.00014','SWE-Bench-CL',['evaluation','experience','repository'],['code','debug','maintain'],
  'Orders software issues chronologically to evaluate experience accumulation, transfer, and forgetting. Its agent evaluation framework includes semantic memory and a protocol comparing memory-enabled and memory-disabled runs.',
  'Chronological repository issue streams and FAISS-backed memory',{write:'Accumulate experience across sequential issues',retrieve:'Semantic memory supports the evaluation framework'},
  'Continual-learning software benchmark based on SWE-bench Verified','The abstract outlines a protocol and preliminary analysis; it does not establish broad memory gains.'],
 ['2307.07924','ChatDev',['collaboration','context'],['plan','code','review','test'],
  'Separates within-phase dialogue memory from solutions retained across phases. Passing completed subtask solutions into later phases preserves workflow continuity without carrying every prior utterance.',
  'Short-term phase utterances and long-term cross-phase solutions',{write:'Record utterances within each phase',retrieve:'Use dialogue history within a phase and prior solutions at the next phase',update:'Append utterances and consolidate completed solutions',forget:'Transmit solutions rather than the complete prior dialogue'},
  'Multi-agent software development','Long-term memory means cross-phase continuity here; persistence across independent projects is not established.','multi-agent'],
 ['2405.15793','SWE-agent Context',['context','governance'],['explore','code','debug','test'],
  'Processes interaction history to keep coding context concise. Recent observations stay detailed, older observations collapse to single lines, and redundant error messages are removed to reduce stale or distracting context.',
  'Action history with detailed recent observations and collapsed older output',{write:'Record commands and observations during a task',retrieve:'Construct the prompt from processed history at each step',update:'Collapse observations older than the latest five',forget:'Remove redundant generation errors and most old observation content'},
  'SWE-bench and history-management ablations','Context management is one part of a broader agent interface; this is within-task working memory.'],
 ['2508.00031','Git Context Controller',['context','repository','collaboration'],['plan','code','reflect','maintain'],
  'Treats coding-agent context as a versioned memory hierarchy. Commit, branch, merge, and context operations checkpoint milestones, isolate alternatives, and support memory recovery or handoff across sessions.',
  'Persistent file-system memory with version-control-style operations',{write:'Commit context at task milestones',retrieve:'Context operations recover retained goals and history',update:'Branch and merge alternative plans and memory'},
  'SWE-bench Lite and an agent-construction case study','Memory scaffolding and agent settings affect reported outcomes; the case study is distinct from benchmark repair.']
];
export const expandedRows=rows.map(r=>[...r.slice(0,6),r[6].write||U,r[6].retrieve||U,r[6].update||U,r[6].forget||U,r[7],r[8],r[9]||'single']);
